### ISSUE TITLE
inactive theme elements are displayed on the edges

### ISSUE THREAD

**Issue by DMITROSE** [PROxZIMA/Sweet-Pop#11]
Hello.
I updated yours, there was a display problem with sites during an active session, inactive elements pop up at the edges and, in short, the screen is narrowed and, as a result, a disgusting view. At the same time, I have several other themes in about: profiles, which are also updated correctly and this problem is not observed on windows 10.
In addition, after cleaning the launch cache, I decided to go to the configure toolbar and make the Restore Defaults, the incomprehensible element appeared as in the address bar.

https://imgur.com/a/6Cd8opc

**Comment by PROxZIMA** [comment]
This is a very weird bug. I tested this theme on Firefox `V96.0` on clean `Windows 11` installation as well as `Pop!_OS 21.10` and both worked out pretty good. I've rolled out a few bug fixes for windows in [`3.1.0`](https://github.com/PROxZIMA/Sweet-Pop/releases/tag/3.1.0) release.

Note: Please lookup to [Installation Step #7](https://github.com/PROxZIMA/Sweet-Pop#installation)

**Comment by DMITROSE** [comment]
Thank you for responding!

I cleaned up prefs.js, everything is fine now, I realized that the problem is that I once set up arkenfox settings.

**Comment by PROxZIMA** [comment]
Glad it worked :)
