### ISSUE TITLE
Floating Navigation with Animated Background not working on Windows 11.

### ISSUE THREAD

**Issue by seventhstorm** [PROxZIMA/Sweet-Pop#14]
The floating navigation and with animated background are not working. I'm running on Windows 11.

**Comment by PROxZIMA** [comment]
Unfortunately I don't have access to Windows 11 as of now. It'll take some time until I test `Sweet-pop` on Windows 11.

> The floating navigation and with animated background are not working. I'm running on Windows 11.

Does `animated background` works when `floating navigation` is turned off?

**Comment by seventhstorm** [comment]
> Unfortunately I don't have access to Windows 11 as of now. It'll take some time until I test `Sweet-pop` on Windows 11.
> 
> > The floating navigation and with animated background are not working. I'm running on Windows 11.
> 
> Does `animated background` works when `floating navigation` is turned off? I'm unable to reproduce this issue on linux.

After a while, I managed to get them working. The only thing that is not running is the navbar for extensions. Everything else seems okay.

**Comment by PROxZIMA** [comment]
> The only thing that is not running is the navbar for extensions

Can you add a screenshot for this?

**Comment by seventhstorm** [comment]
> > The only thing that is not running is the navbar for extensions
> 
> Can you add a screenshot for this?

![image](https://user-images.githubusercontent.com/69987596/163060219-802460ce-7ac2-49fc-b8ab-dc5c98a1dd8b.png)

**Comment by seventhstorm** [comment]
> > > The only thing that is not running is the navbar for extensions
> > 
> > 
> > Can you add a screenshot for this?
> 
> ![image](https://user-images.githubusercontent.com/69987596/163060219-802460ce-7ac2-49fc-b8ab-dc5c98a1dd8b.png)

The tabs part gets crop, not sure how to solve it...

**Comment by seventhstorm** [comment]
> > > > The only thing that is not running is the navbar for extensions
> > > 
> > > 
> > > Can you add a screenshot for this?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69987596/163060219-802460ce-7ac2-49fc-b8ab-dc5c98a1dd8b.png)
> 
> The tabs part gets crop, not sure how to solve it...

**Comment by seventhstorm** [comment]
> > The only thing that is not running is the navbar for extensions
> 
> Can you add a screenshot for this?

![image](https://user-images.githubusercontent.com/69987596/163060664-611ef7a4-ac41-4700-9a62-785123491538.png)

On fullscreen it works fine, no issues.

**Comment by PROxZIMA** [comment]
> The tabs part gets crop, not sure how to solve it...

Checkout #15. I'm trying to figure it out

**Comment by PROxZIMA** [comment]
> I have the exact same problem on Windows 11.

@seventhstorm and @f-x1-1 , the issue is fixed in #20
