### ISSUE TITLE
1920x1080 it hides the upper edge of the window

### ISSUE THREAD

**Issue by zachvlat** [PROxZIMA/Sweet-Pop#15]
![firefox_XR8fOf8YAA](https://user-images.githubusercontent.com/28532979/162391741-1a0c86b3-71de-4253-86dd-d6a8ab3756cc.png)

Firefox 99.0 (64-bit)
Windows 10

**Comment by PROxZIMA** [comment]
Check out the following rule which I wrote specially for Windows 10

https://github.com/PROxZIMA/Sweet-Pop/blob/2336c33bf7b931a52b5b55496fa754d5bafc941b/userChrome.css#L15-L28

I assume that this bug is due to some misalignment in this rule. This will need some debugging on Windows 10 machine.

**Comment by PROxZIMA** [comment]
@zachvlat, the issue is fixed in #20
