### ISSUE TITLE
Broken in Firefox 103

### ISSUE THREAD

**Issue by Lalit64** [PROxZIMA/Sweet-Pop#21]
Hey @PROxZIMA I've got this issue in firefox 103.  ↓

The tab border is broken.

<img width="2662" alt="Screenshot 2022-05-31 at 11 43 38" src="https://user-images.githubusercontent.com/79628080/171144604-a9effad0-ca96-4c7c-b876-8b10e4b4c235.png">

I've re-cloned the repo multiple times and it hasn't worked.

**Comment by PROxZIMA** [comment]
@Lalit64 This issue is fixed on master.
