### ISSUE TITLE
Macos profiles.ini not found

### ISSUE THREAD

**Issue by Gitmaster511** [PROxZIMA/Sweet-Pop#24]
I'm currently running on macos and I tried downloading this using the curl
(curl -s -o- https://raw.githubusercontent.com/PROxZIMA/Sweet-Pop/master/programs/install-curl.sh | bash)
I also tried the installation.sh

But both the times it says profiles.ini not found. I searched the firefox contents and couldn't find a profiles.ini. Do I need to make one?

**Comment by PROxZIMA** [comment]
According to the question mentioned here https://support.mozilla.org/en-US/questions/1152265 the location of `profile.ini` is `~/Library/Application Support/Firefox/`. I'll look into this once I get some time.

Till then see if script installation solves your issue or not. In MacOS case you need to modify `FIREFOXFOLDER` in `./programs/install.sh` on line 4.

**Comment by PROxZIMA** [comment]
Fixed in #27
