### ISSUE TITLE
Empty space at the end of Floating Navigation

### ISSUE THREAD

**Issue by QwertyCoder** [PROxZIMA/Sweet-Pop#25]
I'm running Windows 10, and I've enabled Floating Navigation, but there's an empty space at the top-right corner.
![image](https://user-images.githubusercontent.com/112183558/186927545-4c77bd08-6a92-4982-b44b-cf38a96a2ba1.png)

I've tried selecting it via the Inspector and editing .css files in the Style Editor, but it isn't working. Any fix?

Also, what's the name of this homepage?
![image](https://user-images.githubusercontent.com/112183558/186929719-d8942b39-ab60-4a43-bd4e-2db383be6ae5.png)

Thanks in advance

**Comment by PROxZIMA** [comment]
> I'm running Windows 10

Please mention the Firefox version too

> Also, what's the name of this homepage?

[nightTab](https://addons.mozilla.org/en-US/firefox/addon/nighttab/) by [zombieFox](https://addons.mozilla.org/en-US/firefox/user/15062186/)

**Comment by QwertyCoder** [comment]
![image](https://user-images.githubusercontent.com/112183558/186952306-f24288eb-1c9e-4b86-a5ae-119f85b4501b.png)

**Comment by PROxZIMA** [comment]
Great, I'll install windows and try to reproduce this bug.

> I've tried selecting it via the Inspector and editing .css files in the Style Editor

If you come accross any bugged code then please mention here.

**Comment by QwertyCoder** [comment]
Ok sure, will do...

**Comment by QwertyCoder** [comment]
Hey man, right now I'm using Linux and it's working fine there, so I guess it's a Windows problem.

Now that I've switched, I won't be using Windows again hereafter.
Is it okay if I close the issue?

Thanks for your support...

**Comment by PROxZIMA** [comment]
> Now that I've switched, I won't be using Windows again hereafter.

🤩🤩🤩 I wholeheartedly appreciate this change

> Is it okay if I close the issue?

No, this needs to be fixed. I have to get my hands on windows soon.

**Comment by QwertyCoder** [comment]
Thank you...

Another issue I found when installing Sweet-Pop on Linux (EndeavourOS to be specific), when I tried the Curl based installation,  it tried to paste the 3 files namely user.js, mozilla.cfg and local-settings.js to **usr/bin/firefox** instead of usr/lib/firefox and stated the folder did not exist. So I had to go with the manual installation. Other than that, no issues...

**Comment by PROxZIMA** [comment]
https://github.com/PROxZIMA/Sweet-Pop/blob/8eeb3ce155e5ef78dd077c0521b1b750a7dd8558/programs/install.sh#L95

Take a look at this. Firefox binary location is determined here and then passed on to config installation script.

https://github.com/PROxZIMA/Sweet-Pop/blob/8eeb3ce155e5ef78dd077c0521b1b750a7dd8558/programs/install.sh#L119

I faced this same issue before and current implementation was the closest I could get to find the correct binary path.

It will be better if you open a new issue for this.

Thanks

**Comment by PROxZIMA** [comment]
Fixed in https://github.com/PROxZIMA/Sweet-Pop/commit/07b3d4c3afd4408d23972307e3d585aed21e35f8

You can provide `-b` argument or firefox binary folder

```sh
$ curl -s -o- https://raw.githubusercontent.com/PROxZIMA/Sweet-Pop/master/programs/install-curl.sh | bash -s -- -b /usr/lib/firefox
```
