### ISSUE TITLE
floatingToolbox.uc.js and navbarToolbarButtonSlider.uc.js not working

### ISSUE THREAD

**Issue by QwertyCoder** [PROxZIMA/Sweet-Pop#32]
Hello again, I seem to have this issue where the floating toolbox and colour animation doesn't work and the toolbar button slider doesn't work too.
Right now, I'm using openSUSE Tumbleweed with KDE Plasma with Firefox version 108.0.1 (64-bit).

**Comment by PROxZIMA** [comment]
> colour animation doesn't work

I've made the animated URL as default gradient color.

> floatingToolbox.uc.js and navbarToolbarButtonSlider.uc.js not working

This issue is likely related to `fx-autoconfig` because it loads the `.uc.js` scripts.
---

To fix both issues I'll recommend reinstalling the theme. The old `chrome` folder will be moved to `chrome_bak` automatically.

```bash
curl -s -o- https://raw.githubusercontent.com/PROxZIMA/Sweet-Pop/master/programs/install-curl.sh | bash
```

**Comment by QwertyCoder** [comment]
I followed the script installation method and it worked fine. I didn't do the curl one because of the directory problem I had mentioned before. Thanks man for the support!

Cheers

**Comment by PROxZIMA** [comment]
> I didn't do the curl one because of the directory problem I had mentioned before

```bash
$ curl -s -o- https://raw.githubusercontent.com/PROxZIMA/Sweet-Pop/master/programs/install-curl.sh | bash -s -- -b /usr/bin/firefox
```
Arguments can be provided to the curl command too :p
