### ISSUE TITLE
curl based Installation

### ISSUE THREAD

**Issue by rivando-al-rasyid** [PROxZIMA/Sweet-Pop#38]
its move to bin not to lib

**Comment by PROxZIMA** [comment]
The script looks for the **binary** location.

In some distributions `/usr/bin/firefox/firefox` is the location. But in some distros `/usr/bin/firefox` is a script file which launches `/usr/lib/firefox/firefox` binary. So the script assumes that `/usr/bin` is the folder of the binary.

![image](https://user-images.githubusercontent.com/43103163/219079792-cc93ce17-d2eb-431c-b4b1-a71cfff24f38.png)

**IF** `/usr/bin/firefox` is a script then determining the binary folder location by reading the script is a temporary and terrible solution.  

#### Solution

Add `-b <binary_folder>` to the installation script. More options are mentioned the readme.
