### ISSUE TITLE
Doesnt work in Firefox 90

### ISSUE THREAD

**Issue by Lalit64** [PROxZIMA/Sweet-Pop#4]

**Comment by PROxZIMA** [comment]
![Screenshot from 2021-08-04 20-08-04](https://user-images.githubusercontent.com/43103163/128200614-b500fcd2-ea49-4e75-86d0-3d4a1a1c22a4.png)
Working fine in Firefox 90. Recheck installation process. Installation in wrong profile folder maybe?

**Comment by Lalit64** [comment]
Hello, I don't know what is going on. I am on a mac I copied all the files over.

**Comment by Lalit64** [comment]
Could you provide the css to how you got the overline on the tabs and on the toolbar without them clashing

**Comment by PROxZIMA** [comment]
Tab border is created using
https://github.com/PROxZIMA/Sweet-Pop/blob/86ef35d0386f1be5a6849f94b16df5e75975978a/css/tabbar.css#L33-L67
Toolbox border is created using
https://github.com/PROxZIMA/Sweet-Pop/blob/86ef35d0386f1be5a6849f94b16df5e75975978a/css/tabbar.css#L79-L99

**Comment by Lalit64** [comment]
Thanks @PROxZIMA I forgot to change "browser.proton.enabled" to false
