### ISSUE TITLE
glitches happening in some areas

### ISSUE THREAD

**Issue by ArataKamikaze** [PROxZIMA/Sweet-Pop#5]

**Comment by ArataKamikaze** [comment]
when using a custom themes in windows, i get this weird behaviour where the windows close buttons overlap with the themed ones
![image](https://user-images.githubusercontent.com/49700094/128434063-6fc8f4c3-4427-41ba-a205-62401f785d13.png)
![image](https://user-images.githubusercontent.com/49700094/128434071-139ce98c-7254-47d9-8862-c6ff75878b10.png)
![image](https://user-images.githubusercontent.com/49700094/128434103-dbc88143-ab42-427e-99fc-ef69d041bcbd.png)
i happens whenever i open the browser with the dark theme on and dissapears if i change to the light theme and then back to the dark theme.
Also, when i right click and click on the menu button, the pop up menu has transparent background
![image](https://user-images.githubusercontent.com/49700094/128434256-5478f2e8-e6b4-4446-b259-54555a6af9ff.png)
![image](https://user-images.githubusercontent.com/49700094/128434270-fd8a2f6c-3a74-4d0a-b318-2de19f1e09ef.png)
again, it fixes itself if i change to the light theme and then back to the dark theme.
![image](https://user-images.githubusercontent.com/49700094/128434306-0001294d-6b42-478b-9b65-b5e332cd1faf.png)

**Comment by ArataKamikaze** [comment]
After Some Checking here, i noticed that the problem seems to be caused by the firefox color extension, so i would recommend adding a little comment in the installation guide about trying to disable the extension in case problems appear. since a lot of users start from firefox color and then go to more custom themes like this one.

**Comment by PROxZIMA** [comment]
> when using a custom themes in windows, i get this weird behaviour where the windows close buttons overlap with the themed ones
Was Firefox Color responsible for this too?

**Comment by ArataKamikaze** [comment]
yesterday, i also noticed that by default dark reader also causes the problem.
Changing this option to default like this, fixes the issue:
![image](https://user-images.githubusercontent.com/49700094/128651424-cc03eb3f-1afb-4a44-afae-c0895e945767.png)

**Comment by PROxZIMA** [comment]
Ahh yes, I too came across this one. But I assume there's a limit to what an user themes can style. Still things like Darkreader's `browser theme` or `Firefox Color` overwrite changes after user styles are applied. :)
