### ISSUE TITLE
Old/bugged versions of my scripts

### ISSUE THREAD

**Issue by aminomancer** [PROxZIMA/Sweet-Pop#6]
If you're gonna bundle my scripts with your theme, you should either list my repo as a dependency and direct users to download them from my repo directly, or update the versions on your repo more frequently. The version you have uploaded right now has bugs and has been updated many times in the intervening months, so might cause problems on current versions of firefox. The latest version will always be [at this link](https://github.com/aminomancer/uc.css.js#navbar-toolbar-button-slider). Btw, is MrOtherGuy aware you have a complete copy of fx-autoconfig in this repo? I don't actually bundle his files with my own, I direct users to download them from his repo. In my case, you can't actually share copies of my files here with an MIT license. The 'ShareAlike' clause of my license requires any distributions to use the [exact same license](https://github.com/aminomancer/uc.css.js/blob/master/LICENSE), and include a statement that I hold the copyright to those works. This is significant because my license is immensely more stringent about rights than the MIT license. I don't know about MrOtherGuy's opinion on the matter but his repo has an MPL license. It should be visible in the root directory of his repo. You can change your license the same way, feel free to just copy mine.

**Comment by PROxZIMA** [comment]
I have no idea how this crucial thing missed from my stupid brain -.-
> you should either list my repo as a dependency and direct users to download them from my repo directly

This seems a reasonable choice as users can use your other scripts along with it.
> MrOtherGuy aware you have a complete copy of fx-autoconfig in this repo?

I am really dumb at this point :) I have been going along considering that his repo has an MIT license. I have pulled down `fx-autoconfig` from mine and added a link to his repo.

Thanks for raising this issue. I've updated the README accordingly.

**Comment by aminomancer** [comment]
No worries it's very easy to miss since github doesn't make it very prominent. I'll close the issue then. You can still actually upload my scripts by the way, it just means you have to put them in a subfolder and put the CC license in the subfolder. Same with modifying them
