### ISSUE TITLE
bug with auto-hide scrollbar 

### ISSUE THREAD

**Issue by DMITROSE** [PROxZIMA/Sweet-Pop#7]
I have updated to version 2.0.0 according to the reworked instructions, success, there was no problem with described in this [post](https://www.reddit.com/r/FirefoxCSS/comments/pc7w2t/minor_bugs_appeared_on_the_installed_theme/). But the auto-hide of the scrollbar no longer works for me.
I decided to apply the method as described [here](https://github.com/PROxZIMA/Sweet-Pop/issues/3#issuecomment-863744663), but nothing helped, I made a new profile, but there was also no successful result.

**Comment by PROxZIMA** [comment]
![Screenshot from 2021-08-29 21-26-49](https://user-images.githubusercontent.com/43103163/131256990-4aaf7599-9545-4e8a-9294-216b7f828a00.png)
Check whether `Floating Scrollbar` is enabled. `Toolbar Menu > Tools > userscripts > Floating Scrollbar`. Check-boxes have italics text, enabled check-boxes have bold text.

**Comment by DMITROSE** [comment]
I checked again on the test profile and appeared, as a result, I copied it from the same profile to my main profile, now everything is fine. Thanks
